# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Vagrant Variables

vagrant_box = "bento/ubuntu-16.04"
vagrant_network = "private_network"
vagrant_network_type = 'dhcp'
#vagrant_elasticsearch_install_script = "elasticsearch.sh"
#vagrant_kibana_install_script = "kibana.sh"
#vagrant_logstash_install_script = "logstash.sh"
vagrant_vm_provider = "virtualbox"
#vagrant_guest_kibana_port = 5601
#vagrant_host_kibana_port = 8201
#vagrant_guest_elasticsearch_port = 9200
#vagrant_host_elasticsearch_port = 8200
vagrant_ip_kn = "192.168.51.4"
vagrant_ip_kn1 = "192.168.51.5"
vagrant_ip_kn2 = "192.168.51.6"
zookeeper_ip = "192.168.51.7"

Vagrant.configure("2") do |config|

  config.vm.define "kafka-broker" do |ks|

    ks.vm.hostname = "kafka-broker"
    ks.vm.box = vagrant_box
    ks.vm.network vagrant_network, ip: vagrant_ip_kn
    ks.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #logstash.vm.provision :shell, path: vagrant_logstash_install_script

    ks.vm.provider vagrant_vm_provider do |vb|

      vb.name = "kafka-master"
      vb.memory = "512"

    end

  end

  config.vm.define "kafka-broker-1" do |kn1|

    kn1.vm.hostname = "kafka-broker-1"
    kn1.vm.box = vagrant_box
    kn1.vm.network vagrant_network, ip: vagrant_ip_kn1
    kn1.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #logstash.vm.provision :shell, path: vagrant_logstash_install_script

    kn1.vm.provider vagrant_vm_provider do |vb|

      vb.name = "kn1"
      vb.memory = "512"

    end

  end

  config.vm.define "kafka-broker-2" do |kn2|

    kn2.vm.hostname = "kafka-broker-2"
    kn2.vm.box = vagrant_box
    kn2.vm.network vagrant_network, ip: vagrant_ip_kn2
    kn2.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #logstash.vm.provision :shell, path: vagrant_logstash_install_script

    kn2.vm.provider vagrant_vm_provider do |vb|

      vb.name = "kn2"
      vb.memory = "512"

    end

  end

  config.vm.define "zookeeper" do |zk1|

    zk1.vm.hostname = "zookeeper"
    zk1.vm.box = vagrant_box
    zk1.vm.network vagrant_network, ip: zookeeper_ip
    zk1.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #logstash.vm.provision :shell, path: vagrant_logstash_install_script

    zk1.vm.provider vagrant_vm_provider do |vb|

      vb.name = "zk1"
      vb.memory = "512"

    end

  end

end
